### ISSUE TITLE
Add support for internal (Authlogic_RPX) account mapping

### ISSUE THREAD

**Issue by jjb** [tardate/authlogic_rpx#10]
Allow multiple rpx identifiers to be associated with the same user. See also issue #1 which concerns adding RPX-enabled account mapping.

I would like my users to be able to sign in with any of the available SSO providers.

As it is now, a user account has a single rpx_identifier field, and can only be associated with one SSO provider at a time.

It would be great for a user to be able to have an arbitrary number of rpx_identifiers. This could be done with an entire extra table, or it would perhaps be an okay design to just store this as a serialized ruby array in the db.

If you are interested in supporting this, I would be happy to help writing it.

Thanks for listening,
John

**Comment by tardate** [comment]
Hi John,

Thanks for suggesting this - its one of my "wishlist" items too. In fact, I'm going to close this issue and merge it with #1 - which was essentially the same thing.

One approach for this is to build the capability directly into Authlogic_RPX - as you say, not such a big deal to implement. I hadn't actually been considering going down this path (yet) because RPX inherently supports account mapping. The downside is that it is only in their paid options (one of the reasons I haven't implemented yet - too cheapo to buy a paid subscription yet;-). The benefit is that the mapping is done globally - so if an association has been made by a user using any RPX-enabled site, that mapping would be valid for your site too.

What do you think? Seems like there would be value in having both - a "poor mans mapping" directly supported by Authlogic_RPX, plus support for the RPX-enabled mapping (if you had a subscription that supported it).

**Comment by jjb** [comment]
My previous suggestion of an "easy" implementation using a serialized ruby array in a database field is actually impossible, because when a user authenticates using rpx, the system has to find the user using the rpx_identifier, and that can't be done if they are stored vertically in each row.

So, the only other approach I can think of is to create a new table, perhaps called `rpx_identifiers`. Three columns:
- id
- user_id
- rpx_identifier

I guess one question is, should the single-rpx_identifier in the user table approach continue to be supported, for those people who have more simple needs and don't want to create another table?

I personally can't think of many scenarios where a single SSO service would be sufficient, unless someone is making a system where their intranet OpenID server is being used as a company-wide SSO solution, and they don't care about supporting other endpoints.

Well actually-- in that case, why would they be using RPX instead of just an OpenID consuming library? There, I just answered my own question -- no one will _prefer_ to only support a single service.

Thoughts?

**Comment by jjb** [comment]
Hey Paul-- any thoughts on this? I'm going to get started on an implementation for my purposes over here -- would be great to have some feedback from you.

Cheers,
John

**Comment by tardate** [comment]
Hi John, 
Sorry, seems I missed the notification for your previous update. Great to have you wanting to work on this. I've some time over the next 24 hours - let me get back into the flow of this RPX stuff, I'll send you my thoughts ok?

**Comment by jjb** [comment]
Sounds great, looking forward to it. 

I'm working on writing a test suite right now (which is pretty much a necessity before doing the massive changes in this ticket) -- if you happen to have some uncommitted tests laying around that we can use, let me know.

**Comment by jjb** [comment]
Here's a first stab at multiple accounts:

http://github.com/jjb/authlogic_rpx/commit/92531bd68d5cd9e2a2e98f405724416404dea61d

I gave up on writing tests first, partly because I wanted to hear back from you first, partly because I realized that my code changes weren't that extensive, and partly because I got lazy :) but if you get the initial tests written, I'll be able to help out and will certainly make sure that any changes I contribute are covered by tests.

Anyway-- let me know what you think about my approach in the diff -- meanwhile, I'm going to actually try it out.

**Comment by jjb** [comment]
Here is a bit more work on it, with some comments on what is currently challenging me:

http://github.com/jjb/authlogic_rpx/commit/6bfea06e163989ad89d5eb5566859362e45c3075

**Comment by tardate** [comment]
Thanks for the notes John, I'll take a look soon. Sorry I've not got around to looking into this yet - it's been a busy few days with work and pre-xmas stuff.

**Comment by jjb** [comment]
Okay, I think we've got a pretty good initial working system. I just sent the pull request-- let me know what you think.

**Comment by tardate** [comment]
Hi John (and Damir).
Great work! I just spent a few hours today looking at what you've got. Currently merged back onto a branch "experimental_mapping".

I've made a few enhancements so far:
- preserved backwards compatibility with older installations using user.rpx_identifer (I have a few sites to migrate!)
- moved the rpx_identifiers model into the gem
- added a generator for the rpx_identifiers migration

Done some basic testing - now starting to test some more complex use-cases like adding RPX to existing accounts/dealing with duplicates.

Would you like to pull back from this branch now and see if it works correctly in your scenario?

**Comment by tardate** [comment]
btw, I've been using the sample site on a  similar branch for testing: see http://github.com/tardate/rails-authlogic-rpx-sample/tree/experimental_mapping

**Comment by jjb** [comment]
Great stuff. Trying it out now. A few things I've noticed so far:
- did you intentionally leave out `belongs_to :user` from the RPXIdentifier model?
- in the acts_as_authentic mixin, where a rpx identifier is created in the case that the data is being migrated from the older version (`user.rpx_identifiers.create( :identifier => id )`), should the old identifier field be cleared (set to empty string, or perhaps NULL)) afterward?

**Comment by jjb** [comment]
another very minor thing: any particular reason you create your db indexes outside of the create_table block? Just a visual separation from the schema, or is there some sort of rails performance/maintainability trick I don't know about?

**Comment by tardate** [comment]
re: db indexes =>
I just used the add_index syntax to maintain maximum backward rails compatibility.

Note that I changed the index structure so that we have:
- unique index on identifier, not nullable, to support class.find_by_identifier query path
- non-unique index on user_id, not nullable, to support user.rpx_identifiers query path

**Comment by jjb** [comment]
Sounds great.

**Comment by tardate** [comment]
John, Damir,

I've just pushed some major changes to experimental_mapping ( http://github.com/tardate/authlogic_rpx/tree/e767d52f0766e6722892684bc8ab627ae2dae874 )

These basically provide more flexibility in configuration - you can select mapping mode between:
- :auto (default, tries to smartly select which to use)
- :none (the 1.0.4 approach)
- :internal (the new approach in 1.1.0)
- :rpxnow (for future use)

Let me know your thoughts on this ok?
NB: will checkin some doco updates to match shortly

**Comment by tardate** [comment]
current approach merged into 1.1.0.
Let's close this ticket and follow-up any further issues in new tickets
