### ISSUE TITLE
split experimental map_id features into a separate branch

### ISSUE THREAD

**Issue by jjb** [tardate/authlogic_rpx#11]
What do you think of making a branch of authlogic_rpx with the experimental map_id features? (and taking them out of the master branch).

This would simplify the main code and provide some development compartmentalization and focus.

**Comment by jjb** [comment]
(I updated the ticket, correctly referencing the experimental feature in question)

**Comment by tardate** [comment]
feature development has been merged onto the branch "experimental_mapping"
