### ISSUE TITLE
potential provider_name column issues

### ISSUE THREAD

**Issue by jjb** [tardate/authlogic_rpx#12]
(re: http://github.com/tardate/authlogic_rpx/commit/8fd426675c24d5fd73527caaf475e1baad47d797)

awesome -- that's something i was going to build in my end in a day or two and propose to you. i haven't done any research/experiments with it -- it would be good to be able to be confident about the namespace consistency going forward. a couple things I was going to explore:
- one problem I saw in the RPX docs[1]: if the provider is not "well-known", then the value of providerName is "other".
- a single company with two authentication service. for example, google has its google… thing, but also has a completely separate openid endpoint (google.com/profiles/johnjosephbachir). do they both report the same provider_name?

[1] https://rpxnow.com/docs#profile_data

**Comment by tardate** [comment]
I'm a bit dubious of how trustworthy "providerName" is. At the moment, we record it, but there are no specific interpretations or constraints enforced. The identifier is meant to be unique and should stand alone without needing to consider the providerName

**Comment by jjb** [comment]
It could come in handy for things like counting how many facebook users you have in the system, or applying a function to all facebook users (offering to them to use facebook connect for something…). Have the separate indexed column instead of having to do a regular expression search on the contents of all the identifiers is more efficient and reliable.

The namespace problem is annoying-- RPX should come up with a better solution. like protocol-domain name (facebookconnect-facebook.com, openid-google.com, oauth-twitter, etc). Although then, we'll ask ourselves if a protocol column is needed…

Anyway, just thinking out loud-- I think it's Good Enough for now.

**Comment by tardate** [comment]
Yes, haven't seen this be an issue yet. So parking this issue as "no action for now"

**Comment by tardate** [comment]
closing as of 1.1.0 - case can be re-opened in future if an issue becomes apparent
