### ISSUE TITLE
account merging

### ISSUE THREAD

**Issue by jjb** [tardate/authlogic_rpx#13]
> I've added an some initial account merge capability. adding an already-used ID to another account will cause it to be migrated, with a callback that can be used to migrate application objects if required

http://github.com/tardate/authlogic_rpx/commit/dd63f8c852f8fc5c07439371babcb4f454c9afae

I've been thinking about the account merging case for a few days. It's a big messy problem, in terms of user experience, and is going to change a lot on an application-to-application basis.

And that said, I think your solution is ideal -- let the integrator decide what happens to perform the merge, then you do the merge of the identifiers.

I think the best answer to your question `delete/disable 'another_user' account?` is the simplest one -- just like before the merge, let the integrator decide what to do. Invoke `after_merge_rpx_data`, and in the docs, suggest that this method should probably destroy or disable the old user.

**Comment by tardate** [comment]
I like it.

added `after_merge_rpx_data` - http://github.com/tardate/authlogic_rpx/commit/031d68dfbef2696e7c0cb70dcdc4e18cd9270b90

Need a few extras to give the integrator a bit more positive control I think ... an "enable_account_merging" configuration setting? if return false or throw error from `before_merge_rpx_data` then abort the merge?

**Comment by tardate** [comment]
added an "account_merge_enabled" configuration setting
see http://github.com/tardate/authlogic_rpx/commit/1e9e2fbfd190876b466149ef340748d7d73bff65

**Comment by jjb** [comment]
Great!

**Comment by tardate** [comment]
account merging included in 1.1.0
