### ISSUE TITLE
The sample app failed with rails (2.3.5), rpx_now (0.6.20), authlogic_rpx (1.1.1)

### ISSUE THREAD

**Issue by mcnpx** [tardate/authlogic_rpx#19]
The sample app (http://github.com/tardate/rails-authlogic-rpx-sample) failed with gems versions mentioned in the subj. The error message is http://gist.github.com/385696

Could you test it?

**Comment by mcnpx** [comment]
After some time RPX rejected my app (no changes were made) http://img96.imageshack.us/img96/2508/14128362.png

I am running rails on Windows with cygwin.

**Comment by tardate** [comment]
rpx_now's gone through quite a number of updates; the last version I tested was 0.6.12. Time to bring it up to date...

**Comment by mcnpx** [comment]
I see. Grosser's example fails as well, by the way
http://gist.github.com/386124

**Comment by mcnpx** [comment]
It was my fault. The key was set as an environment variable, but since I use windows, it had trailing \r symbol.

**Comment by tardate** [comment]
ahah;-)

closing this then ... but I'll open a new case to update rpx_now gem support. Getting a bit dated.
