### ISSUE TITLE
facebook access_token with janrain basic account

### ISSUE THREAD

**Issue by badnaam** [tardate/authlogic_rpx#26]
Is this available with a basic account? I would like to make additional calls to the opengraph api if the user logged in with a facebook account, but I am not sure if this is provided by janrain or if there is another way of accessing it

**Comment by tardate** [comment]
Hi badnaam,
It's possible, but only supported by Janrain for Plus and Pro customers. See {auth_info request}[https://rpxnow.com/docs#api_auth_info]

Also see discussion of changes at http://groups.google.com/group/rpx-developers/browse_thread/thread/8d9572e7584a8759/e54a4eeece5e51a2?lnk=gst&q=facebook+access_token#e54a4eeece5e51a2

I'll look to make sure this works as part of adding support for Plus/Pro in authlogic_rpx GH#1.
