### ISSUE TITLE
redirect_back_or_default always goes to 'default'

### ISSUE THREAD

**Issue by findchris** [tardate/authlogic_rpx#27]
I have a product page; when a logged out user logs in from this page using rpx, he is always redirected to the default URL.  

Any way to have the user redirected 'back' to the product page as expected?

Thanks,
Chris

**Comment by tardate** [comment]
Hi Chris,
One approach is used in the sample app. Try the deep link: http://rails-authlogic-rpx-sample.heroku.com/articles/new 

The application controller saves the redirect target as required. See http://github.com/tardate/rails-authlogic-rpx-sample/blob/master/app/controllers/application_controller.rb

**Comment by findchris** [comment]
Hi and thanks for the reply.

My application controller looks the exact same as in the sample app and yet my redirect_back_or_default will always go to my root.

Could this have anything to do with the :return_url option passed to rpx_popup?  The current value is user_sessions_url.

Not sure where else to look.

Thanks.
