### ISSUE TITLE
map_rpx_data in the UserSession model not called with :add_rpx => true

### ISSUE THREAD

**Issue by trooster** [tardate/authlogic_rpx#5]
map_rpx_data in the UserSession model is not called when adding RPX login to an existing account (:add_rpx => true).

It is desirable to call map_rpx_data in the UserSession model when using :add_rpx => true, to allow updating the user record with rpx attributes (like providerName)

**Comment by tardate** [comment]
well spotted. yes, :add_rpx => true doesn't do call map_rpx_data, but I can see why it would be good to have the option.  

Should be possible without too much trouble (nb: under the covers, there's some tricky gymnastics going on at that point to avoid an infinite recursion battle between session and user model)

**Comment by tardate** [comment]
fixed in 1.0.4 release. added map_rpx_data_each_login and map_added_rpx_data hooks
