### ISSUE TITLE
get automated tests working

### ISSUE THREAD

**Issue by tardate** [tardate/authlogic_rpx#7]
To date, I've been manually testing authlogic_rpx. Getting meaningful automated tests working has been a bit of a brain-teaser, since the interesting bits rely on interaction with the external RPX service.

Should get automated tests running, at least to verify the core framework.

**Comment by jjb** [comment]
To write tests which interact with a service, one uses "mock" objects. The most popular solution in ruby is Mocha:

http://mocha.rubyforge.org/

**Comment by tardate** [comment]
got a basic testing framework working on the experimental_mapping branch

**Comment by tardate** [comment]
working tests included in 1.1.0
